/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

namespace RosSharp.RosBridgeClient.MessageTypes.RosScanner
{
    public class PolygonModelRequest : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "RosScanner/PolygonModel";

        public long a;
        public long b;

        public PolygonModelRequest()
        {
            this.a = 0;
            this.b = 0;
        }

        public PolygonModelRequest(long a, long b)
        {
            this.a = a;
            this.b = b;
        }
    }
}
