/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

using RosSharp.RosBridgeClient.MessageTypes.Shape;
using RosSharp.RosBridgeClient.MessageTypes.Geometry;

namespace RosSharp.RosBridgeClient.MessageTypes.RosScanner
{
    public class PolygonModelResponse : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "RosScanner/PolygonModel";

        public MeshTriangle[] triangles;
        public Point[] vertices;

        public PolygonModelResponse()
        {
            this.triangles = new MeshTriangle[0];
            this.vertices = new Point[0];
        }

        public PolygonModelResponse(MeshTriangle[] triangles, Point[] vertices)
        {
            this.triangles = triangles;
            this.vertices = vertices;
        }
    }
}
