/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

namespace RosSharp.RosBridgeClient.MessageTypes.HaoAsakura
{
    public class StartServiceResponse : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "HaoAsakura/StartService";

        public long x1;
        public long y1;
        public long x2;
        public long y2;
        public string material;

        public StartServiceResponse()
        {
            this.x1 = 0;
            this.y1 = 0;
            this.x2 = 0;
            this.y2 = 0;
            this.material = "";
        }

        public StartServiceResponse(long x1, long y1, long x2, long y2, string material)
        {
            this.x1 = x1;
            this.y1 = y1;
            this.x2 = x2;
            this.y2 = y2;
            this.material = material;
        }
    }
}
